# Generated by Django 4.1.5 on 2023-02-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_publish',
            field=models.BooleanField(default=True),
        ),
    ]
