# Generated by Django 4.1.5 on 2023-02-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_is_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='contacts/profile_pictures/%Y/%m/%d/'),
        ),
    ]
