# Generated by Django 4.1.5 on 2023-02-06 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_contact_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='author',
        ),
    ]
